config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  resources :categories do
    get 'all-categories', on: :collection
  end
  root to: 'static_pages#home'
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  belongs_to :parent_category, class_name: "Category", optional: true
  has_many :subcategories, class_name: "Category", foreign_key: "parent_category_id", dependent: :destroy
  has_many :expenses
  validates :name, presence: :true, uniqueness: { case_sensitive: false }
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :category
  validates :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validate :validate_username

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  attr_writer :login

  def login
    @login || self.username || self.email
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      conditions[:email].downcase! if conditions[:email]
      where(conditions.to_h).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /categories
  def index
  end

  def all_categories
    @categories = Category.where(parent_category: nil)
    render partial: 'all_categories'
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  def new_subcategory
    @parent_category = Category.find(params[:id])
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)
    @category.user = current_user

    @category.save
  end

  def create_subcategory
    @category = Category.new(category_params)
    @category.user = current_user

    @category.save
  end

  # PATCH/PUT /categories/1
  def update
    @category.update(category_params)
    respond_to do |f|
      f.js
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def category_params
    params.require(:category).permit(:name, :parent_category_id)
  end
end

app/controllers/expenses_controller.rb
require 'json'

class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]
  before_action :change_amounts_comma_to_dot, only: [:create, :update]
  before_action :authenticate_user!

  # GET /expenses
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  def create
    puts "------------------ #{expense_params}"
    if expense_params.empty?
      redirect_to new_expense_path, alert: 'Error'
      return
    end
    Expense.transaction do
      expense_params.each {|expense| Expense.create(expense)}
    redirect_to new_expense_path, notice: 'Expenses were created'
    end
  end


  # PATCH/PUT /expenses/1
  def update
    if @expense.update(expense_params)
      redirect_to @expense, notice: 'Expense was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /expenses/1
  def destroy
    @expense.destroy
    redirect_to expenses_url, notice: 'Expense was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def expense_params
    JSON.parse params.require(:expenses)
  end

  def change_amounts_comma_to_dot
    JSON.parse(params[:expenses]).each {|expense| expense["amount"].gsub!(',', '.')}
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/categories/_all_categories.html.erb
<% @categories.each do |category| %>
  <div style="background-color: bisque; margin: 10px 0; padding: 10px">
    <%= render 'category', category: category %>
    <ul class="subcategories">
      <% category.subcategories.each do |subcategory| %>
        <li>
          <%= render 'category', category: subcategory %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/categories/_category.html.erb
<div class="category-div" data-category-id='<%= category.id %>'>
  <div class="category-name"><%= category.name %></div>
  <button class="edit-category-btn">Edit</button>
  <div class="edit-category-div" style="display: none">
    <input value="<%= category.name %>">
    <button class="save-category-btn">Save</button>
    <button class="discard-edit-category-btn">Discard changes</button>
  </div>
  <button class="delete-category-btn">Delete</button>
  <% unless category.parent_category.present? %>
    <button class="new-subcategory-btn">New subcategory</button>
    <ul class="new-subcategory-div" style="display: none">
      <li>
        <input>
        <button class="add-subcategory-btn">Add</button>
        <button class="discard-subcategory-btn">Discard changes</button>
      </li>
    </ul>
  <% end %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @parent_category.present? %>
    <%= form.hidden_field :parent_category_id, value: @parent_category.id %>
  <% end %>
  <div class="field">
    <%= form.text_field :name %><%= form.submit %>
  </div>

<% end %>

app/views/categories/index.html.erb
<div>
  <h1>Categories</h1>
  <div id="categories">
    <div>
      <button id="new-category-btn">New category</button>
      <div id="add-category-div" style="display: none">
        <input />
        <button id="add-category-btn">Add</button>
        <button id="discard-category-btn">Discard</button>
      </div>
    </div>
    <div id="all-categories"></div>
  </div>
</div>

app/views/expenses/_form.html.erb
<%= form_with(model: expense, local: true, id: 'expenses-form') do |form| %>
  <% if expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= collection_select :expense, :category_id, Category.order(:name), :id, :name, {prompt: 'Select category'},
                          {class: 'selectize', id: 'selectCategory', required: true} %>
    <span class="form-error" aria-live="polite"></span>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount,
                        {autocomplete: 'off',
                         pattern: '[0-9]+([,\.][0-9]{1,2})?',
                         value: number_with_precision(form.object.amount, precision: 2),
                         required: true
                         } %>
    <span class="form-error" aria-live="polite"></span>
  </div>

  <div class="actions">
    <button id="add-expense-btn" type="button">Add expense</button>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<h1>Expenses</h1>

<table>
  <thead>
  <tr>
    <th>Date</th>
    <th>Amount</th>
    <th>Category</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @expenses.each do |expense| %>
    <tr>
      <% if expense.date.nil? %>
        <td>no date</td>
      <% else %>
        <td><%= expense.date.strftime('%d.%m.%Y') %></td>
      <% end %>
      <td><%= number_with_precision(expense.amount, precision: 2, locale: :pl) %></td>
      <td><%= expense.category.name %></td>
      <td><%= link_to 'Show', expense %></td>
      <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
      <td><%= link_to 'Destroy', expense, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<%= link_to 'Back', expenses_path %>
<h1>New Expense</h1>

<%= render 'form', expense: @expense %>

<button id="create-expenses">Send expenses</button>

<div id="expenses"></div>

app/views/expenses/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @expense.date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>Category:</strong>
  <%= @expense.category.name %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpensesManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p id="notice"><%= notice %></p>
  <p id="alert"><%= alert %></p>

  <%= yield %>

  <%= yield :javascript %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Expenses Manager</h1>

<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam,
  feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies
  mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi,
  condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum
  rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent
  dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat.
  Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>

<% if current_user %>
  <%= link_to "Categories", categories_path %>
  <%= link_to "Expenses", expenses_path %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Log in", new_user_session_path %><br/>
  <%= link_to "Sign up", new_user_registration_path %><br/>
<% end %>